Slurm Support v0 (#4)
* slurm init

* increase env vars for testing

* manager tempalte implementations

* accel

* refractor, not linted yet

* merge conflicts

* integration

* remove cli manager checker, allow skylet manager to return its api
response instead. Move watcher import inside of init function to avoid
circular import

* clean

* global define, manager refractor to style

* manager aliases

* slurm manager refrac for lint and yapf

* refrac, clean

* premerge

* slurm demo

* remove unused classes

* add template functions

* lint

* lint, unowned

* container manager compat, tests

* fix integration between cli and manager

* linting

* refractor, not linted yet

* clean

* remove unused classes

* Merge

* Delete examples/example_simple.yaml

* update newest compat layer for slurm

* pylint and slurm cli ver

* slurmcli

* slurmcli commit, full pipeline tested

* sample slurm config for ~/.skyconf/slurmconf.yaml

* Readme for slurm

* Add requests_unixsocket to requirements  (#107)

* Update setup.py

Launching the API server in a fresh conda environment with the slurm branch installed (and the slurm branch with main merged in) produces the following stack trace. Adding `requests_unixsocket` to setup.py[server] produces the same results as the "apparent resolution" below.


Stack trace
```
$ python api_server/launch_server.py --workers=1
[Installer] ETCD is running.
API server config already exists. Skipping generation.
Traceback (most recent call last):
  File "/Users/tester/Documents/GitHub/skyflow/api_server/launch_server.py", line 103, in <module>
    main(args.host, args.port, args.workers, args.data_directory)
  File "/Users/tester/Documents/GitHub/skyflow/api_server/launch_server.py", line 60, in main
    uvicorn.run(
  File "/Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages/uvicorn/importer.py", line 22, in import_from_string
    raise exc from None
  File "/Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/tester/Documents/GitHub/skyflow/api_server/api_server.py", line 22, in <module>
    from skyflow.cluster_manager.kubernetes_manager import K8ConnectionError
  File "/Users/tester/Documents/GitHub/skyflow/skyflow/cluster_manager/__init__.py", line 6, in <module>
    from skyflow.cluster_manager.manager_utils import setup_cluster_manager
  File "/Users/tester/Documents/GitHub/skyflow/skyflow/cluster_manager/manager_utils.py", line 12, in <module>
    from skyflow.cluster_manager.slurm_manager_rest import SlurmManagerREST
  File "/Users/tester/Documents/GitHub/skyflow/skyflow/cluster_manager/slurm_manager_rest.py", line 12, in <module>
    import requests_unixsocket
ModuleNotFoundError: No module named 'requests_unixsocket'
```

Apparent resolution
```
$ pip install requests_unixsocket
Collecting requests_unixsocket
  Downloading requests_unixsocket-0.3.0-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: requests>=1.1 in /Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages (from requests_unixsocket) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages (from requests>=1.1->requests_unixsocket) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages (from requests>=1.1->requests_unixsocket) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages (from requests>=1.1->requests_unixsocket) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /Users/tester/miniconda3/envs/skyflow-slurm/lib/python3.9/site-packages (from requests>=1.1->requests_unixsocket) (2024.2.2)
Downloading requests_unixsocket-0.3.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: requests_unixsocket
Successfully installed requests_unixsocket-0.3.0
$ python api_server/launch_server.py --workers=1
[Installer] ETCD is running.
API server config already exists. Skipping generation.
INFO:     Started server process [96288]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:50051 (Press CTRL+C to quit)
```

* Update setup.py

* adapted SLURM compatibility layer to multiple containers per task

* Add slurm supported controllers check to skylet, do avoid starting unsupported controllers. Add support for multiple different slurm clusters to be attached. Modified skylet_controller to pass entire cluster object instead of just name. Updated readme and exmaples. Simplified slurm init configuration control flow. Removed cli --namespace forced option requirement

* readme and example to reflect multiple cluster support

* Localized slurm testing support, initial podman and podman-hpc support.
Container manager discovery function

* update readme

* Removed PDB lines.

* Min resource defaults for job submission. Initial Passkey support

* configuration verification, global definitions, compat layer refractor

* Fixed some nits that broke the branch.

* ssh utils

* refractor, and config verification before manager initialization

* improve logging

* fix parse error I think

* fix parse error I think

* add auto cluster lookup for slurm

* Add gpus to job resources (#181)

* remote debug and unused from cluster lookup

* remvoe debug statements and unused vars.

* Reorder and cleanup files

* remove unneeded edits

* Clean up slurm authentication and config

* Clean up everything except Slurm folder and tests

* partial push

* init push

* Clean up Rest API defer to future Skyflow PR

* Remove slurm rest api test, defer to futur ePR

* temp push

* Working Slurm end2end

* Robustify code

* Format.sh

* add Readme

* Update batch_job.yaml

* remove yaml

* add paramiko dependency

* Fix bugs from merge

* cope

* Merge wtih Ray PR

* Fix tests?

* Some comments

* Address comments

* Fix api tests

* fix

---------

Co-authored-by: Michael Luo <michael.luo@berkeley.edu>
Co-authored-by: MEllis-github <21113023+MEllis-github@users.noreply.github.com>
Co-authored-by: Alexmontoril23 <alex.cl.2000@gmail.com>